In [1]:
import numpy as np
dataset_filename = "affinity_dataset.txt"
X = np.loadtxt(dataset_filename)

In [2]:
print(X[:5])

[[ 0.  0.  1.  1.  1.]
 [ 1.  1.  0.  1.  0.]
 [ 1.  0.  1.  1.  0.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  1.  0.  0.  1.]]


In [3]:
 print(X.head)

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [4]:
dir(X)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',


In [5]:
# First, how may rows contain our premise: that a person is buying apples
num_apple_purchases = 0
for sample in X:
    if smaple[3] == 1: # This person bought Apples
        num_apple_purchase += 1
        
print("{0} people bought Apples.".format(num_apple_purchases))

NameError: name 'smaple' is not defined

In [6]:
# First, how may rows contain our premise: that a person is buying apples
num_apple_purchases = 0
for sample in X:
    if sample[3] == 1: # This person bought Apples
        num_apple_purchase += 1
        
print("{0} people bought Apples.".format(num_apple_purchases))

NameError: name 'num_apple_purchase' is not defined

In [7]:
# First, how may rows contain our premise: that a person is buying apples
num_apple_purchases = 0
for sample in X:
    if smaple[3] == 1: # This person bought Apples
        num_apple_purchases += 1
        
print("{0} people bought Apples.".format(num_apple_purchases))

NameError: name 'smaple' is not defined

In [8]:
# First, how may rows contain our premise: that a person is buying apples
num_apple_purchases = 0
for sample in X:
    if sample[3] == 1: # This person bought Apples
        num_apple_purchases += 1
        
print("{0} people bought Apples.".format(num_apple_purchases))

36 people bought Apples.
